/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastrarRouteImport } from './routes/cadastrar'
import { Route as DadosRouteImport } from './routes/dados'
import { Route as MusicasRouteImport } from './routes/musicas'
import { Route as RepertoriosIndexRouteImport } from './routes/repertorios.index'
import { Route as RepertoriosIdRouteImport } from './routes/repertorios.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarRoute = CadastrarRouteImport.update({
  id: '/cadastrar',
  path: '/cadastrar',
  getParentRoute: () => rootRouteImport,
} as any)
const DadosRoute = DadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicasRoute = MusicasRouteImport.update({
  id: '/musicas',
  path: '/musicas',
  getParentRoute: () => rootRouteImport,
} as any)
const RepertoriosIndexRoute = RepertoriosIndexRouteImport.update({
  id: '/repertorios/',
  path: '/repertorios/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepertoriosIdRoute = RepertoriosIdRouteImport.update({
  id: '/repertorios/$id',
  path: '/repertorios/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastrar': typeof CadastrarRoute
  '/dados': typeof DadosRoute
  '/musicas': typeof MusicasRoute
  '/repertorios/$id': typeof RepertoriosIdRoute
  '/repertorios/': typeof RepertoriosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastrar': typeof CadastrarRoute
  '/dados': typeof DadosRoute
  '/musicas': typeof MusicasRoute
  '/repertorios/$id': typeof RepertoriosIdRoute
  '/repertorios': typeof RepertoriosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastrar': typeof CadastrarRoute
  '/dados': typeof DadosRoute
  '/musicas': typeof MusicasRoute
  '/repertorios/$id': typeof RepertoriosIdRoute
  '/repertorios/': typeof RepertoriosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastrar'
    | '/dados'
    | '/musicas'
    | '/repertorios/$id'
    | '/repertorios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastrar'
    | '/dados'
    | '/musicas'
    | '/repertorios/$id'
    | '/repertorios'
  id:
    | '__root__'
    | '/'
    | '/cadastrar'
    | '/dados'
    | '/musicas'
    | '/repertorios/$id'
    | '/repertorios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastrarRoute: typeof CadastrarRoute
  DadosRoute: typeof DadosRoute
  MusicasRoute: typeof MusicasRoute
  RepertoriosIdRoute: typeof RepertoriosIdRoute
  RepertoriosIndexRoute: typeof RepertoriosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar': {
      id: '/cadastrar'
      path: '/cadastrar'
      fullPath: '/cadastrar'
      preLoaderRoute: typeof CadastrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dados': {
      id: '/dados'
      path: '/dados'
      fullPath: '/dados'
      preLoaderRoute: typeof DadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musicas': {
      id: '/musicas'
      path: '/musicas'
      fullPath: '/musicas'
      preLoaderRoute: typeof MusicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repertorios/': {
      id: '/repertorios/'
      path: '/repertorios'
      fullPath: '/repertorios/'
      preLoaderRoute: typeof RepertoriosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repertorios/$id': {
      id: '/repertorios/$id'
      path: '/repertorios/$id'
      fullPath: '/repertorios/$id'
      preLoaderRoute: typeof RepertoriosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastrarRoute: CadastrarRoute,
  DadosRoute: DadosRoute,
  MusicasRoute: MusicasRoute,
  RepertoriosIdRoute: RepertoriosIdRoute,
  RepertoriosIndexRoute: RepertoriosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
